# Generated by Django 6.0.5 on 2026-05-20 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(max_length=255)),
                ('descricao_completa', models.TextField()),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Identificador')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('regras_aluguel', models.TextField(blank=True, help_text='Ex: Devolver limpo, não usar na terra.', null=True)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status_atual', models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20)),
                ('idade_recomendada', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brinquedos', to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('endereco_padrao', models.TextField(help_text='Endereço principal para entrega')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prazo_aluguel', models.IntegerField(choices=[(7, '7 Dias'), (15, '15 Dias'), (30, '30 Dias')])),
                ('tipo_logistica', models.CharField(choices=[('entrega', 'Entrega'), ('retirada', 'Retirada')], max_length=20)),
                ('endereco_entrega', models.TextField(blank=True, help_text='Preencher se for entrega', null=True)),
                ('status_aluguel', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_andamento', 'Em Andamento (Alugado)'), ('concluido', 'Concluído / Devolvido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='catalogo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_no_momento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_pedidos', to='catalogo.brinquedo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='catalogo.pedido')),
            ],
        ),
    ]
