# Generated by Django 6.0.5 on 2026-05-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brinquedo',
            name='imagem_url',
        ),
        migrations.CreateModel(
            name='ImagemBrinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_url', models.URLField(max_length=500)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='0 será a foto principal da capa, 1 em diante no carrossel')),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.brinquedo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
