# Generated by Django 6.0.5 on 2026-06-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_brinquedo_imagem_url_imagembrinquedo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='faixa_etaria',
            field=models.CharField(blank=True, choices=[('ate_1', 'Até 1 ano'), ('1_3', '1 a 3 anos'), ('3_6', '3 a 6 anos'), ('6_10', '6 a 10 anos'), ('10+', 'Acima de 10 anos')], max_length=10, null=True, verbose_name='Faixa Etária'),
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='fase',
            field=models.CharField(blank=True, choices=[('bebe', 'Bebê'), ('engatinhando', 'Engatinhando'), ('andando', 'Andando'), ('escolar', 'Escolar')], max_length=15, null=True, verbose_name='Fase do Desenvolvimento'),
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='tipo_uso',
            field=models.CharField(blank=True, choices=[('festa', 'Festa'), ('educativo', 'Educativo'), ('externo', 'Ao ar livre'), ('interno', 'Interno')], max_length=15, null=True, verbose_name='Tipo de Uso'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prazo_aluguel',
            field=models.IntegerField(choices=[(1, 'Diária'), (7, '7 Dias'), (15, '15 Dias'), (30, '30 Dias')]),
        ),
    ]
