# Generated by Django 6.0.5 on 2026-05-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao_curta', models.CharField(max_length=255)),
                ('descricao_completa', models.CharField()),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Identificador')),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status_atual', models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20)),
                ('idade_recomendada', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brinquedos', to='core.categoria')),
            ],
        ),
    ]
